apiVersion: v1
kind: ServiceAccount
metadata:
  name: minerva
  namespace: minerva
  labels:
    app: minerva
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minerva
  namespace: minerva
  labels:
    app: minerva
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["minerva-config"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minerva
  namespace: minerva
  labels:
    app: minerva
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minerva
subjects:
- kind: ServiceAccount
  name: minerva
  namespace: minerva
