apiVersion: v1
kind: Service
metadata:
  name: minerva
  namespace: minerva
  labels:
    app: minerva
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: minerva
  ports:
  - name: api
    port: 3000
    targetPort: api
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: minerva-headless
  namespace: minerva
  labels:
    app: minerva
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: minerva
  ports:
  - name: api
    port: 3000
    targetPort: api
    protocol: TCP
